service: default
runtime: python37
instance_class: F4
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api_folder.main:app

env_variables:
  DB_USER: 'gAAAAABiJoGk7NPCI5dpjFgllYIdxTy6LHKb48KNP6Gv3qaMJO5UqS6d3-eqKj93UFexTHSVixTN0iPf0vHytZI4UDq6w1wClQ=='
  PASSWORD: 'gAAAAABiJoQuMjEDYj_zzspyV_07jh0y5RDfTqPRLeOZUAlQ8XDRIrcg-oDnB1GQJ4wL7h-k2fxkzU_yPUu4SG0DCupkQh4fCA=='
  IP: 'gAAAAABinLyYidmSPjpZkn7e5CfU8_26-bNmgQwMlWxE1LZs-SjBNcXlbi3OdUrAQJOYW9ECHNbzXnfn__5g2opj3llcgyFtQQ=='
  SCHEMA: Prod
  NUMBER: 'gAAAAABjHjIynArWDaQdLz-68tRONsbrHPir-uUKqtA1s22Ycjm5FtuY0d3zoLlkmoB9WEYXxLqQIPuKK8nvW-NW6to_u2dn1w=='
  SID: 'gAAAAABjHjI9Lxg-ckrSMa6FVlwHDFcf3UKB8FBHKnS-vMNv1Y5AR0hTwYhsuSN8TKNIrxLuUCjwpfESW-BqBKAs3EYCY_kwCQn8KfM_Fx5Z4s6CPUtsLPGy09eyRytgc44-Ls2Q-s7H'
  TOKEN: 'gAAAAABjHjJGgHNH3bj6hd1o5OPI_xAcM9YxT3nQeza90Vj28X9AOgZI_xur9R0RWDV0TnEE36AkQndPiIll0P51TEUYbt1yo8OZuaR7Ea8O5_fxrZTDs2O2qZv7h9Ipn1e36X9cF3S3'